ARG NODE_VERSION="20.17"

FROM docker.io/node:${NODE_VERSION}-alpine3.19

ENV NPM_CONFIG_UPDATE_NOTIFIER=false
ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

EXPOSE 3000
EXPOSE 4200
EXPOSE 5000

RUN apk add --no-cache \
	pkgconfig \
	gcc \
	pixman-dev \
	cairo-dev \
	pango-dev \
	make \
	build-base

RUN apk add --no-cache \
	caddy \
	supervisor \
	bash=5.2.21-r0

COPY .env.example /app/.env
COPY devops/var/docker/entrypoint.sh /app/entrypoint.sh
COPY devops/var/docker/Caddyfile /app/Caddyfile
COPY devops/var/docker/supervisord.conf /etc/supervisord.conf
COPY devops/var/docker/supervisord /app/supervisord_configs/

COPY nx.json tsconfig.base.json package.json package-lock.json build.plugins.js /app/
COPY apps /app/apps/
COPY libraries /app/libraries/

RUN npm install

VOLUME /config
VOLUME /uploads

RUN chmod 775 /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]